#define GROUND_IMG_WIDTH 640
#define GROUND_IMG_HEIGHT 20
extern unsigned long ground_img[400];

#define DINO_IMG_WIDTH 96
#define DINO_IMG_HEIGHT 96
extern unsigned long dino_images[5][288];

#define CACTUS_IMG_WIDTH 32
#define CACTUS_IMG_HEIGHT 64
extern unsigned long cactus_image[64];

#define PTERO_IMG_WIDTH 96
#define PTERO_IMG_HEIGHT 64
extern unsigned long ptero_images[2][192];

#define SPLASH_WIDTH 640
#define SPLASH_HEIGHT 400
extern unsigned long start_screen [8000];
extern unsigned long end_screen [8000];