CC = cc68x
CFLAGS = -g -c
OBJS = main.o raster.o render.o fbuff.o model.o sound.o get_time.o song.o dino_img.o ground~1.o cactus~1.o ptero_~1.o
PROG = dino

all: $(PROG)

clean:
	$(RM) *.o *.~ $(PROG)

$(PROG): $(OBJS)
	$(CC) -g $(OBJS) -o $(PROG)

main.o: main.c model.h render.h raster.h fbuff.h boolean.h
	$(CC) -c main.c

raster.o: raster.c raster.h boolean.h
	$(CC) -c raster.c

render.o: render.c render.h raster.h model.h images.h
	$(CC) -c render.c

fbuff.o: fbuff.c fbuff.h raster.h boolean.h
	$(CC) -c fbuff.c

model.o: model.c model.h boolean.h images.h
	$(CC) -c model.c

sound.o: sound.c sound.h song.h
	$(CC) -c sound.c

get_time.o: get_time.c get_time.h
	$(CC) -c get_time.c

song.o: song.c song.h
	$(CC) -c song.c

dino_img.o: dino_img.c images.h
	$(CC) -c dino_img.c

ground~1.o: ground~1.c images.h
	$(CC) -c ground~1.c

cactus~1.o: cactus~1.c images.h
	$(CC) -c cactus~1.c

ptero_~1.o: ptero_~1.c images.h
	$(CC) -c ptero~1.c