void render_game(unsigned long *base, struct Model *model);

void render_dino(unsigned long *base, struct Model *model);
void clear_dino(unsigned long *base, struct Model *model);
void render_ground(unsigned long *base, struct Model *model);
void clear_ground(unsigned long *base, struct Model *model);
void render_start(unsigned long *base);
void render_end(unsigned long *base);
void clear_splash(unsigned long *base);
void render_obstacles(unsigned long *base, struct Model *model);
void clear_obstacles(unsigned long *base, struct Model *model);